

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Providers as ChackraProvider } from '@/chackraui/providers/providers'
import SideBarDrawerContext from '@/contexts/SideBarDrawerContext'
import ReactQueryProvider from '@/services/reactQuerySetup'





const roboto = Roboto({ subsets: ['latin'] ,
weight:["400","500","700"]})

export const metadata: Metadata = {
  title: 'dashgo',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryProvider>
          <SideBarDrawerContext>
            <ChackraProvider>
             {children}
            </ChackraProvider>
            </SideBarDrawerContext>
            </ReactQueryProvider>
          
        </body>
    </html>
  )
}
